# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 03:39
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180131_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
